### ISSUE TITLE
invalid service notification

### ISSUE THREAD

**Issue by ghost** [D-clock/AndroidDaemonService#21]
应用中报出的错误

```
Fatal Exception: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```
手机型号 Lenovo TAB 3 850F  系统版本6.0

有没有解决办法

**Comment by venkatesh87** [comment]
I'm facing the same issue. any solution?

**Comment by ghost** [comment]
try catch , do nothing , i did not find the solution, if you find it, let me known please
